### ISSUE TITLE
Adaptive delay

### ISSUE THREAD

**Issue by tuhdo** [tsdh/highlight-parentheses.el#12] opened 2015-04-15 17:37 UTC
@tsdh Since your PR fixed the performance issue, it's great. However, I think we can do better to make it smoother for small buffer by adjusting the delay value based on buffer size. For example, starting from 10k buffer, the delay is 0.01. Every additional 10k add 0.01 to the starting 0.01, i.e. if I opened a 100k buffer the delay is 0.1 and when capped at 0.23 when it reaches this value. What do you think?

@nschum what do you think?

**Comment by tsdh** [comment] 2015-04-16 05:40
@tuhdo I don't have strong opinion here.  But the delay should be at least larger than the keyboard repeat rate which is not accessible from emacs, I think.

How about a new option `hl-paren-delay` which can either be a fixed decimal or a function of zero args?  If it is a function, it is called with the relevant buffer being current, and it should return a decimal which is then used as delay value in the current buffer.

**Comment by tuhdo** [comment] 2015-04-16 05:52
> If it is a function, it is called with the relevant buffer being current, and it should return a decimal which is then used as delay value in the current buffer.

Yes, I think so. We decide the delay based on the buffer size. You may choose the suitable starting value as you see fit though, i.e. you may try on a 100k buffer with 0.01 to see if there's any problem, so we can safely use it for 10k buffer.

**Comment by tsdh** [comment] 2015-04-16 06:36
I think a decimal-valued `hl-paren-delay` is enough.  If you want, you can set it buffer-locally in `highlight-parentheses-mode-hook` based on whatever you like.

And by the way, I don't see why buffer size would matter for the delay. The only reason why larger buffers seem to be less responsive than small buffers (when scrolling) is that lazy font-locking kicks in.  After you have scrolled the complete buffer or ran `(font-lock-ensure)` once to force the whole buffer to be fontified, they should be almost as responsive as small buffers.  So basically, you might want a larger delay in case you scroll into a region of the buffer which hasn't been fontified yet but I think this information is not accessible.

**Comment by tuhdo** [comment] 2015-04-16 06:57
Ok that's fine to me. `0.137` is good enough. But for large buffer, why lazy font lock makes a different in small and large buffer? Is it slower to process on large buffer?

**Comment by tsdh** [comment] 2015-04-16 07:11
@tuhdo Perfect, then I'll close the issue.

I don't know exactly how font-lock works in details.  I think with small buffers you don't usually notice it because when you scroll, you reach the buffer end/start pretty soon and font-lock and redisplay catch up.  When scrolling in large buffers, the requests for font-locking the regions you scrolled over and the required redisplays sum up pretty soon and need to be processed one-after the other.  That can easily cause a hang for some seconds even after you already stopped scrolling.

Of course, also the complexity of the font-lock rules and the sizes of the functions/procedures in the buffer are important.  Some font-lock rules can't simply start anywhere but they need to restart at some safe anchor point, e.g., the beginning of a function definition.  c-mode is an extreme example here.  Try opening Emacs' `buffer.c` and scroll from top to bottom.  Or just call `(font-lock-ensure)`.  That can easily take more than ten seconds because the C syntax is so complex and the functions are large.

**Closed by tsdh** 2015-04-16 07:11 UTC

**Comment by tuhdo** [comment] 2015-04-16 07:19
I opened 39MB C file in my Ubuntu machine with no lagging at all, except a slight delay when jump to a far away line. No editing or scrolling lag at all.

**Comment by tuhdo** [comment] 2015-04-16 07:24
Here is the demo [opening 39MB C file](http://tuhdo.github.io/static/performance.gif). You will see I jumped to line 1,000,000 there.

**Comment by tsdh** [comment] 2015-04-16 12:21
@tuhdo To trigger font-lock the regions have to become visible.  Thus jumping to some fixed line or `M-<` and `M->` are cheap because only the visible part of the buffer around the jump position are to be fontified.

Try opening the file so that point is on the first line, and then press & hold `C-v` or `C-n` instead until you reach the end of the buffer.  That should take very long, and at some point you will encounter hangs during scrolling.  I can easily reproduce that using `emacs -Q` and then scrolling emacs' `buffer.c` file which is only about 6000 lines long.

What you can also try is opening some buffer and then do `M-: (font-lock-ensure)`.  That takes at least 20 seconds here with `buffer.c`.  With your 39MB file it might take orders of magnitudes more.

**Comment by tuhdo** [comment] 2015-04-16 18:53
I never have any problem for souce files around 10k-50k lines. For example, opening vhdl-mode.el.gz which has over 17k lines, I can press and hold C-M-e until the end of file. Same for C file.  I had no problem with a 5k lines C source file with continuous scrolling. In addition to that, I'm using Spacemacs with has over 100 packages built-in. Probably it has something to do with your configuration or Your chosen Emacsgui toolkit?

**Comment by tuhdo** [comment] 2015-04-16 18:56
Or probably I raised gc-cons-threshold to 100MB so no GC activity happens when working with such large files.

**Comment by tsdh** [comment] 2015-04-16 19:21
I use GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.2) as of today.  I can reproduce the hang during scrolling easily using `emacs -Q` and `vhdl-mode.el` for example.  I can also reproduce the issue with `emacs -Q -nw` which should exclude the toolkit as the culprit.  Raising `gc-cons-threshold` doesn't help, too.

When I open `buffer.c`, do `M-x profiler-start`, then scroll the complete buffer until I reach the bottom (after a hang of about 20 secs), and then do `M-x profiler-report`, that's what I get:

```
- command-execute                                               53434  97%
 - call-interactively                                           53434  97%
  - funcall-interactively                                       53354  97%
   - scroll-up-command                                          53329  97%
    - scroll-up                                                 52925  96%
     - jit-lock-function                                        52922  96%
      - jit-lock-fontify-now                                    52922  96%
       - jit-lock--run-functions                                52815  96%
        - run-hook-wrapped                                      52815  96%
         - #<compiled 0x512e33>                                 52815  96%
          - font-lock-fontify-region                            52811  96%
           - c-font-lock-fontify-region                         52811  96%
            - font-lock-default-fontify-region                  50983  93%
             - font-lock-fontify-keywords-region                50627  92%
              + c-font-lock-declarations                        47110  86%
              + c-font-lock-enclosing-decls                      2396   4%
              + c-font-lock-complex-decl-prepare                  195   0%
              + #<compiled 0x516f6b>                              116   0%
                #<compiled 0x516bc3>                              105   0%
              + c-font-lock-enum-tail                              93   0%
                #<compiled 0x4e7549>                               81   0%
                #<compiled 0x516c01>                               69   0%
                #<compiled 0x516c1d>                               66   0%
              + #<compiled 0x516fa1>                               65   0%
                #<compiled 0x4e7565>                               48   0%
              + #<compiled 0x50fa9f>                               37   0%
                #<compiled 0x516ff7>                                7   0%
             + font-lock-fontify-syntactically-region                342   0%
            + c-before-context-fl-expand-region                  1821   3%
         #<compiled 0x549fb3>                                      94   0%
     + eval                                                         3   0%
   + execute-extended-command                                      25   0%
  + byte-code                                                      80   0%
+ ...                                                            1257   2%
+ redisplay_internal (C function)                                  60   0%
+ timer-event-handler                                               5   0%
```

So as you can see, 97% of the time is spent in font-lock code.

Did you really try with `emacs -Q`?  Do you have some specific font-lock tuning code in your `~/.emacs`?  And what is your emacs version?  (I just found out that it seems to be much slower with emacs 24.4 than with a build of the current git HEAD.  But even with that I can reproduce the hangs although they are much shorter.)

**Comment by tsdh** [comment] 2015-04-16 21:31
Oh, above I've meant that emacs 24.4 is faster than my current emacs git HEAD build.  However, I have diagnosed that this comes mostly from the CFLAGS used for building where I disable all optimizations etc from the emacs I'm hacking on.

Now that we're talking about it, I've looked into the docs again and found out about deferring JIT lock and stealth lock.  With these settings, I can also scroll fast in any buffer:

```elisp
(setq jit-lock-defer-time 0.0312
      jit-lock-stealth-nice 0.117
      jit-lock-stealth-time 0.5)
```

But of course, when scrolling over buffer portions that haven't been fontified yet, they are only displayed in the default face.  When I stop scrolling, the visible buffer portion is jit-locked after 0.0312 seconds.  And the stealth-lock thingy font-locks the complete buffer portion by portion when emacs is idle.  Cool stuff!

Now I really wonder if you have similar customization or why your emacs is so much faster than mine.  I've tried a lot of stuff including different or no X toolkits, and nothing makes much of a difference with `emacs -Q`.

**Comment by tuhdo** [comment] 2015-04-17 02:44
Here is the result I got when using `emacs -Q` and did not set anything, on `buffer.c`:

```text
- redisplay_internal (C function)                         248,322,774  53%
 - jit-lock-function                                      222,342,592  47%
  - jit-lock-fontify-now                                  222,318,672  47%
   - funcall                                              222,048,073  47%
    - #<compiled 0x1195d59>                               222,048,073  47%
     + run-hook-with-args                                 222,048,073  47%
     vconcat                                                      990   0%
 + tool-bar-make-keymap                                    25,010,228   5%
   file-remote-p                                              480,878   0%
 + eval                                                       327,220   0%
 + kill-this-buffer-enabled-p                                 104,656   0%
 + #<compiled 0x3e89f9>                                        32,240   0%
 + keymap-canonicalize                                          4,160   0%
   menu-bar-update-buffers                                      2,080   0%
- command-execute                                         203,383,959  43%
 - call-interactively                                     203,378,759  43%
  - scroll-up-command                                     131,027,826  28%
   - scroll-up                                            130,720,956  28%
    - jit-lock-function                                   130,376,292  28%
     - jit-lock-fontify-now                               130,363,812  28%
      - funcall                                           130,349,348  28%
       + #<compiled 0x118fcf1>                            130,349,348  28%
      file-remote-p                                           256,396   0%
    + eval                                                     88,268   0%
  + byte-code                                              42,985,586   9%
  + find-file                                              16,735,228   3%
  + execute-extended-command                                5,286,324   1%
  + describe-bindings                                       4,575,310   0%
  + quit-window                                             1,533,751   0%
  + next-line                                                 750,977   0%
  + previous-line                                             152,876   0%
  + minibuffer-complete-and-exit                              131,166   0%
  + profiler-report-toggle-entry                              124,251   0%
  + kill-ring-save                                             40,968   0%
  + scroll-down-command                                        23,056   0%
  + handle-focus-in                                             2,080   0%
+ xselect-convert-to-string                                13,047,765   2%
+ timer-event-handler                                          32,240   0%
+ xselect-convert-to-targets                                   25,984   0%
+ #<compiled 0x3bbdc9>                                         16,896   0%
+ blink-cursor-end                                              2,080   0%
  x-set-selection                                               1,256   0%
+ deactivate-mark                                                 216   0%
  ...                                                               0   0%
```

I had to slow while continuously pressing `C-v`. For `vhdl-mode.el`, I jammed the `C-v` key until the end:

```text
- command-execute                                                1572  62%
 - call-interactively                                            1566  62%
  - scroll-up-command                                            1455  58%
   - scroll-up                                                     27   1%
    - eval                                                         13   0%
       if                                                           9   0%
      file-remote-p                                                 8   0%
  + byte-code                                                      92   3%
  + execute-extended-command                                       19   0%
- redisplay_internal (C function)                                 810  32%
 - jit-lock-function                                              717  28%
  - jit-lock-fontify-now                                          660  26%
   - funcall                                                      620  24%
    - #<compiled 0x4bfc13>                                        616  24%
     + run-hook-with-args                                         616  24%
      #<compiled 0x4856c7>                                          4   0%
 - tool-bar-make-keymap                                            19   0%
  + tool-bar-make-keymap-1                                         12   0%
   file-remote-p                                                   16   0%
 + #<compiled 0x3e89f9>                                            15   0%
 + kill-this-buffer-enabled-p                                      12   0%
 + eval                                                            12   0%
 + and                                                              4   0%
+ ...                                                             116   4%
```

My Emacs did not spend significant time on font lock like yours, and I built it with standard configuration: `./configure --with-x-toolkit=gtk3 && make && sudo make install`.

**Comment by tuhdo** [comment] 2015-04-17 02:45
My Linux is Ubuntu 14.04 kernel 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tuhdo** [comment] 2015-04-17 02:46
I'm using the recently released Emacs 24.5 and nothing fancy.

**Comment by tsdh** [comment] 2015-04-17 03:07
@tuhdo Really strange.  I'll just also tried with Emacs 24.5 and it's subjectively a bit faster but also hangs during scrolling with a similar profiler stat to the one I've posted before.

The main difference between mine and your profiler stats is that with mine `redisplay_internal` has zero or almost zero percentage.  That's the indication of the hangs during scrolling, i.e., font-lock is so busy that no redisplay is possible anymore.  What I see when pressing and holding `C-v` in a freshly opened larger lisp or C buffer is that for one or two seconds, the buffer contents scrolls up, and then display freezes.  After several seconds of emacs using 100% of one CPU redisplay kicks in again.  At that point in time I've already reached the buffer end.  So the buffer contents between the portion where the freeze started and the buffer end has never been visible to me.

I'll try to check if I can reproduce that on other machines, too.

And just to be sure: you don't own some extremely super-fast quantum computer, no?  My laptop has an Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz and tons of RAM (16GB).  Of course, emacs uses just one core out of the four, but that's still a reasonably fast system where emacs shouldn't be lagging because of too low resources.

**Comment by tuhdo** [comment] 2015-04-17 04:22
My computer actually has lower spec than yours:

```text
> sudo lshw -C cpu
PCI (sysfs)  


  *-cpu                   
       description: CPU
       product: Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
       vendor: Intel Corp.
       physical id: 2b
       bus info: cpu@0
       version: Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
       slot: CPU
       size: 933MHz
       capacity: 2266MHz
       width: 64 bits
       clock: 1066MHz
       capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid cpufreq
       configuration: cores=2 enabledcores=2 threads=4

```

```text
> sudo lshw -C memory
  *-firmware              
       description: BIOS
       vendor: INSYDE
       physical id: 0
       version: 1.30
       date: 05/06/2010
       size: 1MiB
       capacity: 1472KiB
       capabilities: pci upgrade shadowing cdboot bootselect edd int13floppynec int13floppytoshiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int9keyboard int10video acpi usb biosbootspecification
  *-memory
       description: System Memory
       physical id: 19
       slot: System board or motherboard
       size: 4GiB
```

I have no problem on my work machine (the above spec), my macbook air and my sluggish Windows machine.

**Comment by tsdh** [comment] 2015-04-17 05:38
@tuhdo This drives me nuts.  I tested on another machine with emacs 24.3, and there I get the same hangs.

Then on yet another machine with emacs 23.4, scrolling is very fast.  No hang at all.  On the same machine with emacs from git HEAD, I get the hangs again.

On a virtualbox windows image with emacs 24.4, scrolling is fast and there are no real hangs.  This might be caused because there the keyboard repeat rate is lower, though, so the scroll speed is less than on the other machines I tested.  I configured it to 1ms which is the fastest repeat rate you can use.

**Comment by tsdh** [comment] 2015-04-17 06:38
@tuhdo BTW, I can reproduce the long freezes only with `buffer.c` (or another long C file), lisp files such as `vhdl-mode.el` scroll reasonably fast with just some short hangs from time to time.  And only with emacs 24.5 only if I use a graphical frame, i.e., `emacs -Q` and not `emacs -nw -Q`.  Did you use a graphical frame?

With emacs from the git HEAD, I get the long freezes also with `-nw`.

**Comment by tuhdo** [comment] 2015-04-17 06:41
@tsdh yes. All the tests I did were in graphical Emacs, not terminal and I jammed `C-v` in `vhdl-mode.el` until the end without any problem.

did the profiler reports give the same traces between your tested machines? In my case, the font locking is performed in my `redisplay-function` which is a C function and probably that's why its fast, why yours is performed at the time of scrolling. Did you try all with just `emacs -Q`?

**Comment by tuhdo** [comment] 2015-04-17 06:44
What's your Linux? Maybe you could test it on another Linux like a virtual machine Ubuntu?

**Comment by tuhdo** [comment] 2015-04-17 06:54
Fyi, I append `buffer.c` a few times into another C file to create a 50k lines source file for testing and then I pressed `C-v` (and held it at the beginning)  until the last line without any problem.

**Comment by tsdh** [comment] 2015-04-17 07:28
As said, lisp files scroll reasonably fast for me, too.  Only large and complex C files trigger the freeze.

I'm on Arch and tested also with some (remote) machines, one of which also run Ubuntu.  And there I also became the freezes.

And yes, all tests were performed with `emacs -Q` both with a graphical frame and with a tty frame.
What do you mean with your `redisplay-function` is a C function and thus it is fast?  There is no function or variable of that name in my emacs.  Do you mean `redisplay_internal`?  That's of course also in C here.

**Comment by tsdh** [comment] 2015-04-17 07:53
Could you please do a test for me.

Create a file `~/fle.el` with the contents:

```elisp
(defun font-lock-ensure ()
  (font-lock-set-defaults)
  (jit-lock-fontify-now))
```

Then start emacs using `emacs -Q --load ~/fle.el path/to/buffer.c`.

Once the buffer is opened (and you haven't scrolled in there yet), do `M-: (benchmark-run (font-lock-ensure)) RET`.  That will print a list of three numbers to *Messages* which I would like to know.

The first number is the time in seconds that was used by `(font-lock-ensure)`.  Here, it is 3.4 for the current emacs-24 branch (which is almost identical to the released emacs 24.5), and about 6 seconds for the current git HEAD.

**Comment by tuhdo** [comment] 2015-04-17 14:08
Here is the result when I tried with Emacs 24.5 on Windows 7 with Spacemacs installed:

```text
(7.2774163 4 0.4240244000000004)
```

Here is the result with `emacs -Q`:

```text
(8.1334652 102 1.7541005000000003)
```

Even on my Windows machine, pressing `PgDown` (not holding it) is really smooth. No delay or freezing at all.

**Comment by tsdh** [comment] 2015-04-17 14:43
So your emacs is actually slower font-locking than mine while still being smooth during scrolling.  That's strange.  What is your keyboard repeat rate?  You can query that using `xset -q`.

Here is my output:

```
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000000
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  625    repeat rate:  58
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  11/2    threshold:  5
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  0
Colors:
  default colormap:  0x22    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/misc/,/usr/share/fonts/TTF/,/usr/share/fonts/Type1/,built-ins
DPMS (Energy Star):
  Standby: 0    Suspend: 0    Off: 0
  DPMS is Enabled
  Monitor is On
```

As you can see, I have a repeat rate of 58 Hz, that is, 58 repeats per second.  Maybe this calls `scroll-up` too often and thus causes the display freezes...

**Comment by tuhdo** [comment] 2015-04-17 15:42
Hmm on Windows the `KeyboardSpeed` value is 31 in `HKEY_CURRENT_USER\Control Panel\Keyboard` which means 31 repetitions per second. On my Ubuntu machine at work, it's something like 250ms though, so probably it could solve your problem.

**Comment by tsdh** [comment] 2015-04-17 18:52
Heh, indeed.  When I drastically reduce the kbd repeat rate, scrolling becomes much smoother.  Too bad I do like such a high repeat rate.  So I'll stick to deferred and stealth JIT-lock.

Bug good that we've talked about it and finally found out what's the difference. :+1:

**Comment by tuhdo** [comment] 2015-04-23 06:33
@tsdh today I setup Emacs for a machine and when I use Emacs I encountered something similar to your issue: it starts lagging with not really large file. Then I remember that in my old config, I increased `gc-cons-threshold` much higher:

```elisp
(setq gc-cons-threshold 100000000) ;; 100 MB before GC cleanup things
```

Add it and it becomes much smoother.

**Comment by tsdh** [comment] 2015-04-23 07:46
No, the windows seeing means 31 ms delay between repetitions. And 250 ms would be encoded as a repeat rate of 4 Hz. You see, the systems use different measures for the repeat rate.

This doesn't have much to do with GC, at least not in my case.
